version: '3.1'
services:
  product-ms-database-service:
    container_name: product-ms-database-container
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - product-ms-network
    volumes:
      - product-ms-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product-ms-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  product-ms-application-service:
    container_name: product-ms-application-container
    image: product-ms
    ports:
      - "9999:9999"
    networks:
      - product-ms-network
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - product-ms-database-service
    environment:
      MYSQL_HOST: product-ms-database-service

networks:
  product-ms-network:

volumes:
  product-ms-volume:
